package:
  name: concave_hull
  version: 0.0.2

source:
  path: ..

build:
  number: 0
  script: python -m pip install . -vvv

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - cmake
    - ninja

  host:
    - python
    - pip !=22.1.0

  run:
    - python


test:
  requires:
    - pytest
    - numpy
  imports:
    - concave_hull
  source_files:
    - tests
  commands:
    - python -m pytest

about:
  summary: A very fast 2D concave hull algorithm
  license_file: LICENSE
